package org.test.firebase.pushservice.model.entity;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

/**
 * Entity class representing a user's Firebase Cloud Messaging token.
 * 'user_tokens' database table, stores token information.
 */
@Data
@Entity
@Table(name = "user_tokens")
public class UserToken {
    /**
     * Primary key, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * Firebase registration token.
     */
    @Column(name = "token", nullable = false, unique = true)
    private String token;

    /**
     * Unique identifier of the user associated with the token.
     */
    @Column(name = "user_id", nullable = false, unique = false)
    private String userId;

    /**
     * Timestamp of when the token was registered.
     * Automatically set by Hibernate when the entity is created.
     */
    @CreationTimestamp
    @Column(name = "creation_time", nullable = false)
    private LocalDateTime time;

}
